# Generated by Django 5.0.3 on 2024-04-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alumni_alter_volunteer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=12)),
                ('Department', models.CharField(max_length=122)),
                ('Abroad', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Department', models.CharField(max_length=12)),
                ('Options', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Department', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=12)),
                ('Volunteer_as', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='alumni',
        ),
        migrations.DeleteModel(
            name='volunteer',
        ),
    ]
