# Generated by Django 5.0.3 on 2024-04-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alumnis_registrations_volunteers_delete_alumni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='preference',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
