# Generated by Django 5.0.3 on 2024-04-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_registrations_preference'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alumnis',
            new_name='alumniss',
        ),
        migrations.RenameModel(
            old_name='registrations',
            new_name='registrationss',
        ),
        migrations.RenameModel(
            old_name='volunteers',
            new_name='volunteerss',
        ),
    ]
