# Generated by Django 5.0.3 on 2024-04-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_alumnis_alumniss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=12)),
                ('Department', models.CharField(max_length=122)),
                ('Abroad', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Department', models.CharField(max_length=12)),
                ('Options', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('preference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.CharField(max_length=122)),
                ('Department', models.CharField(max_length=122)),
                ('Phone', models.CharField(max_length=12)),
                ('Volunteer_as', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='alumniss',
        ),
        migrations.DeleteModel(
            name='registrationss',
        ),
        migrations.DeleteModel(
            name='volunteerss',
        ),
    ]
